//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ExampleSets = newExampleSetsTable("public", "example_sets", "")

type exampleSetsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ExampleSetsTable struct {
	exampleSetsTable

	EXCLUDED exampleSetsTable
}

// AS creates new ExampleSetsTable with assigned alias
func (a ExampleSetsTable) AS(alias string) *ExampleSetsTable {
	return newExampleSetsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ExampleSetsTable with assigned schema name
func (a ExampleSetsTable) FromSchema(schemaName string) *ExampleSetsTable {
	return newExampleSetsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ExampleSetsTable with assigned table prefix
func (a ExampleSetsTable) WithPrefix(prefix string) *ExampleSetsTable {
	return newExampleSetsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ExampleSetsTable with assigned table suffix
func (a ExampleSetsTable) WithSuffix(suffix string) *ExampleSetsTable {
	return newExampleSetsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newExampleSetsTable(schemaName, tableName, alias string) *ExampleSetsTable {
	return &ExampleSetsTable{
		exampleSetsTable: newExampleSetsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newExampleSetsTableImpl("", "excluded", ""),
	}
}

func newExampleSetsTableImpl(schemaName, tableName, alias string) exampleSetsTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{CreatedAtColumn}
	)

	return exampleSetsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
