//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type RuntimeStatistics struct {
	ID                     int64 `sql:"primary_key"`
	MaximumTimeMillis      int64
	MaximumMemoryKibibytes int64
	TotalTimeMillis        int64
	TotalMemoryKibibytes   int64
	AvgTimeMillis          float64
	AvgMemoryKibibytes     float64
}
