//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type TaskSubmissions struct {
	ID                int64 `sql:"primary_key"`
	UserID            int64
	TaskID            int64
	ProgrammingLangID string
	Submission        string
	CreatedAt         time.Time
	Hidden            bool
	VisibleEvalID     *int64
}
