package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"fmt"
)

// ExecuteCode is the resolver for the executeCode field.
func (r *mutationResolver) ExecuteCode(ctx context.Context, code string, languageID string) (*ExecutionResult, error) {
	panic(fmt.Errorf("not implemented: EnqueueSubmission - enqueueSubmission"))
}
