package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
)

// ListLanguages is the resolver for the listLanguages field.
func (r *queryResolver) ListLanguages(ctx context.Context, enabled *bool) ([]*ProgrammingLanguage, error) {
	// TODO: implement ListLanguages endpoint
	panic("not implemented")

	//languages, err := langs.ListEnabledProgrammingLanguages(r.PostgresDB)
	//if err != nil {
	//	return nil, err
	//}
	//
	//// convert to graphql type
	//var gqlLangs []*ProgrammingLanguage
	//for _, lang := range languages {
	//	gqlLangs = append(gqlLangs, internalProgrammingLanguageToGraphQL(&lang))
	//}
	//
	//return gqlLangs, nil
}
