// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Constraints struct {
	TimeLimitMs   int `json:"timeLimitMs"`
	MemoryLimitKb int `json:"memoryLimitKb"`
}

type Description struct {
	ID       string     `json:"id"`
	Story    string     `json:"story"`
	Input    string     `json:"input"`
	Output   string     `json:"output"`
	Examples []*Example `json:"examples,omitempty"`
	Notes    string     `json:"notes"`
}

type Example struct {
	ID     string `json:"id"`
	Input  string `json:"input"`
	Output string `json:"output"`
}

type ExecutionResult struct {
	Stdout string `json:"stdout"`
	Stderr string `json:"stderr"`
}

type Language struct {
	ID       string `json:"id"`
	FullName string `json:"fullName"`
	MonacoID string `json:"monacoID"`
}

type Metadata struct {
	Authors []string `json:"authors,omitempty"`
	Origin  *string  `json:"origin,omitempty"`
}

type Submission struct {
	ID       string    `json:"id"`
	Task     *Task     `json:"task"`
	Language *Language `json:"language"`
	Code     string    `json:"code"`
}

type Task struct {
	ID          string       `json:"id"`
	Code        string       `json:"code"`
	Name        string       `json:"name"`
	Description *Description `json:"Description"`
	Constraints *Constraints `json:"Constraints"`
	Metadata    *Metadata    `json:"Metadata"`
	CreatedAt   string       `json:"createdAt"`
	UpdatedAt   string       `json:"updatedAt"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
