package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"

	"golang.org/x/crypto/bcrypt"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, password string) (*User, error) {
	// validate registration data
	if username == "" || password == "" {
		return nil, fmt.Errorf("username and password are required")
	}
	if len(password) < 8 {
		return nil, fmt.Errorf("password must be at least 8 characters")
	}
	if len(password) > 32 {
		return nil, fmt.Errorf("password must be at most 32 characters")
	}
	if len(username) < 3 {
		return nil, fmt.Errorf("username must be at least 3 characters")
	}
	if len(username) > 15 {
		return nil, fmt.Errorf("username must be at most 15 characters")
	}

	// check if user with the same username already exists
	var userWithUsernameCount int
	err := r.DB.QueryRow("SELECT COUNT(*) FROM users WHERE username = ?", username).Scan(&userWithUsernameCount)
	if err != nil {
		return nil, err
	}

	if userWithUsernameCount > 0 {
		return nil, fmt.Errorf("user with that username already exists")
	}

	// hash password
	var hashedPassword []byte
	hashedPassword, err = bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return nil, err
	}
	password = string(hashedPassword)

	// create user
	_, err = r.DB.Exec("INSERT INTO users (username, password) VALUES (?, ?)", username, password)
	if err != nil {
		return nil, err
	}

	// temporary
	return &User{
		ID:       "1",
		Username: username,
	}, nil
}

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, username string, password string) (*User, error) {
	// just to test whether sql works
	// return row count in table flyway_schema_history as user id

	rows := r.DB.QueryRow("SELECT COUNT(*) FROM flyway_schema_history")
	var count int
	err := rows.Scan(&count)
	if err != nil {
		return nil, err
	}

	// temporary
	return &User{
		ID:       fmt.Sprintf("%d", count),
		Username: "test",
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
