//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Evaluations struct {
	ID                      int64 `sql:"primary_key"`
	EvalStatusID            string
	EvalTotalScore          int64
	EvalPossibleScore       *int64
	TestRuntimeStatisticsID *int64
	CompilationDataID       *int64
	CreatedAt               time.Time
}
