//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FlywaySchemaHistory struct {
	InstalledRank int32 `sql:"primary_key"`
	Version       *string
	Description   string
	Type          string
	Script        string
	Checksum      *int32
	InstalledBy   string
	InstalledOn   time.Time
	ExecutionTime int32
	Success       bool
}
