//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type StatementExamples struct {
	ID            int64
	Input         string
	Answer        string
	TaskVersionID int64
}
