//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type SubmissionEvaluations struct {
	ID                  int64 `sql:"primary_key"`
	TaskSubmissionID    int64
	EvalTaskVersionID   int64
	TestMaximumTimeMs   *int64
	TestMaximumMemoryKb *int64
	TestTotalTimeMs     int64
	TestTotalMemoryKb   int64
	EvalStatusID        string
	EvalTotalScore      int64
	CompilationStdout   *string
	CompilationStderr   *string
	CompilationTimeMs   *int64
	CompilationMemoryKb *int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	EvalPossibleScore   *int64
}
