//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type TaskVersions struct {
	ID            int64 `sql:"primary_key"`
	TaskID        int64
	ShortCode     string
	FullName      string
	TimeLimMs     int64
	MemLimKb      int64
	TestingTypeID string
	Origin        *string
	CreatedAt     time.Time
	UpdatedAt     *time.Time
	CheckerID     *int64
	InteractorID  *int64
}
