//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TaskVersionTests struct {
	ID               int64 `sql:"primary_key"`
	TestFilename     string
	TaskVersionID    int64
	InputTextFileID  int64
	AnswerTextFileID int64
}
