//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Tasks struct {
	ID               int64 `sql:"primary_key"`
	CreatedAt        time.Time
	CreatedByID      int64
	CurrentVersionID *int64
	StableVersionID  *int64
}
