//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type VersionSolution struct {
	ID                   int64 `sql:"primary_key"`
	TaskVersionID        *int64
	ProgrammingLangID    *string
	Solution             *string
	CreatedAt            *time.Time
	Hidden               *bool
	ExpectedEvalStatusID *int64
}
