package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"
)

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, username string, password string) (*User, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
