name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: krisjanisp/proglv-backend

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to DH
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Create kubernetes directory
      run: mkdir -p kubernetes

    - name: Download manifest
      run: wget https://raw.githubusercontent.com/programme-lv/devops/main/kubernetes/programme.lv/backend_deployment.yaml -P kubernetes/

    - name: Replace manifest tokens
      run: |
        sed -e 's/latest/${{env.DOCKER_METADATA_OUTPUT_VERSION}}/g' \
            < ./kubernetes/proglv_backend_deployment.yaml > ./kubernetes/gucci_deployment.yaml

    - name: Log manifest
      run: cat ./kubernetes/gucci_deployment.yaml

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f ./kubernetes/gucci_deployment.yaml

    - name: Verify deployment
      run: timeout 30s kubectl rollout status deployment/backend -n proglv

    - name: Display running pods
      run: kubectl get pods -n backend
